fesbuk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import user_status.urls as user_status
import user_profile.urls as user_profile
import user_friends.urls as user_friends
import user_stats.urls as user_stats

urlpatterns = [
	url(r'^$', RedirectView.as_view(url='status/', permanent=True), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include(user_status,namespace='status')),
    url(r'^profile/', include(user_profile,namespace='profile')),
    url(r'^friends/', include(user_friends,namespace='friends')),
    url(r'^stats/', include(user_stats,namespace='stats')),
]

user_friends/urls.py
from django.conf.urls import url
from .views import index, add_friend
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
]

user_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

user_stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

user_status/urls.py
from django.conf.urls import url
from .views import index, add_status
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-status', add_status, name='add-status')
]

user_friends/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.TextField()
    added_date = models.DateTimeField(auto_now_add=True)

user_profile/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length = 100)
    birthday = models.DateField()
    gender = models.CharField(max_length = 10)
    #expertise = models.CharField(max_length = 100) 
    description = models.TextField()
    email = models.EmailField()

user_stats/models.py
from django.db import models

# Create your models here.

user_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

user_friends/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    name_attrs = {
        'type': 'text',
        'class': 'name-form',
        'placeholder': 'Masukan nama...',
    }
    url_attrs = {
        'type': 'text',
        'class': 'url-form',
        'pattern': '^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$',
        'placeholder': 'Masukan url... (ex: http://fesbuk.herokuapp.com)',
    }

    name = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=name_attrs))
    url = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=url_attrs))

user_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
    'required' : 'Tolong isi input ini'
    }

    status_attrs = {
    'type' : 'text',
    'placeholder' : "Masukkan status...",
    'cols' : 50,
    'rows' : 4,
    'class' : 'status-form-textarea'
    }

    status = forms.CharField(label='', required=True, max_length=150, widget=forms.Textarea(attrs=status_attrs))

user_friends/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

# Create your views here.

author = "Kelompok 8A"
response = {}

def index(request):
	response["author"] = author
	html = "user_friends/user_friends.html"
	friend = Friend.objects.all()
	friend = reversed(friend)
	response['friend'] = friend
	response["friend_form"] = Friend_Form
	return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friend(name=response['name'],url=response['url'])
        friend.save()
        return HttpResponseRedirect('/friends/')
    else:
        return HttpResponseRedirect('/friends/')

user_profile/views.py
from django.shortcuts import render
from .models import Profile

response = {}

#bio_dict = [{'subject' : 'Birthday', 'value' : ':  ' + calculate_age(birth_date)},\
    #{'subject' : 'Gender', 'value' : ':  ' + user_gender},\
	#{'subject' : 'Description', 'value' : ':  ' + user_description},\
	#{'subject' : 'Email', 'value' : ':  ' + user_mail}]

#bio_name = [{'subject' : user_name}]

def index(request):
    profile = Profile.objects.get(pk=1)
    response['profile'] = profile
    return render(request, 'user_profile/user_profile.html', response)

user_stats/views.py
import sys
sys.path.append(sys.path[0] + '/..')

from django.shortcuts import render
from user_profile.views import Profile
from user_status.models import Status
from user_friends.models import Friend

response = {}

def index(request):
	profile = Profile.objects.get(pk=1)
	response['profile'] = profile

	status_count = len(Status.objects.all())
	response['status_count'] = status_count

	friend_count = len(Friend.objects.all())
	response['friend_count'] = friend_count

	qs = Status.objects.order_by('-created_date')
	if(len(qs) > 0):
		latest_post = qs[0]
	else:
		latest_post = None

	response['latest_post'] = latest_post

	html = 'user_stats/user_stats.html'

	return render(request, html, response)

user_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Status
from .forms import Status_Form
from user_profile.models import Profile

# Create your views here.
response = {}

def index(request):
    profile = Profile.objects.get(pk=1)
    response['profile'] = profile
    response['list'] = Status.objects.all()
    response['update_status_form'] = Status_Form
    html = "user_status/user_status.html"
    return render(request, html, response)

def add_status(request):
    if(request.method == 'POST' and Status_Form(request.POST or None).is_valid()):
        Status(status=request.POST['status']).save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="OH">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}"/>

    {% block style %}
        <!-- custom styling goes here -->
    {% endblock %}

    <title>
        {% block title %} Fesbuk {% endblock %}
    </title>

</head>

<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        {% include "partials/footer.html" %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript" src=""></script>
</body>
</html>

templates/partials/footer.html
<div class="footer">
	<hr>
	<p>Made with &lt;3 by Kelompok 8</p>
</div>

templates/partials/header.html
 <!-- templates/lab_5/partials/header.html -->
 <html>
   <body>
     <div class="header">
       <div class="left-side">
         <div class="title">
           <p>Fesbuk</p>
         </div>
       </div>
       <div class="right-side">
        <div class="flex-box">
          <a href="/status">
            <p>Home</p>
          </a>
        </div>
        <div class="flex-box">
          <a href="/profile">
            <p>Profile</p>
          </a>
          </div>
         <div class="flex-box">
           <a href="/friends">
             <p>Friends</p>
           </a>
         </div>
         <div class="flex-box">
           <a href="/stats">
             <p>Stats</p>
           </a>
         </div>
       </div>
     </div>
   </body>
 </html>

user_friends/templates/user_friends/user_friends.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}
Friends
{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_friends.css' %}"/>
{% endblock %}

  {% block content %}
    <div class= "contain">
      <form class= "friend-form" method="POST" action="{% url 'friends:add_friend' %}">
        <h2>Add Friend</h2>
        {% csrf_token %}
        {{ friend_form }}
        <button class="friend-button">Add friend</button>
      </form>
    </div>
    <div class= "contain">
      <h2>Friend List</h2>
      <div class= "flex">
        {% if friend %}
          {% for data in friend %}
            <div class= "flex-item">
              <div class= "friend">
                <div class= "friend-name">
                  {{ data.name }}
                </div>
                <a class= "friend-url" target="_new" href="{{ data.url }}">
                  {{ data.url }}
                </a>
                <div class= "friend-added-date">
                  {{ data.added_date }}
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
        {% endif %}
      </div>
    </div>
  {% endblock %}

user_profile/templates/user_profile/user_profile.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}
Profile
{% endblock %}

{% block style %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_profile.css' %}"/>
{% endblock %}

{% block content %}
<div class="center_up">
  <h3>Profile</h3>
  <img src="https://cdn4.iconfinder.com/data/icons/linecon/512/photo-128.png" alt="Profile Picture">
  <h1 style="text-align:center">{{ profile.name }}</h1>
</div>
<div class="center_down">
  <table align="center" style="text-align: center">
            <tr>
                <td class="subject">Birth date</td>
                <td class="value">: {{ profile.birthday }}</td>
            </tr>
            <tr>
                <td class="subject">Gender</td>
                <td class="value">: {{ profile.gender }}</td>
            </tr>
            <tr>
                <td class="subject">Description</td>
                <td class="value">: {{ profile.description }}</td>
            </tr>
            <tr>
                <td class="subject">Email</td>
                <td class="value">: {{ profile.email }}</td>
            </tr>
  </table>
  <br><br>
</div>
{% endblock %}

user_stats/templates/user_stats/user_stats.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %} Statistics {% endblock %}

{% block style %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_stats.css' %}"/>
{% endblock %}

{% block content %}
	<section name="basic-stats" id="basic-stats">
		<div class="container">
			<div class="stats-profile">
  				<img src="https://cdn4.iconfinder.com/data/icons/linecon/512/photo-128.png" alt="Profile Picture">
				<h4>{{ profile.name }}</h4>
			</div>
			<div class="stats-count">
				<p>Friends: {{ friend_count }} People</p>
				<p>Feed: {{ status_count }} Posts</p>
			</div>
		</div>
	</section>
	<section name="latest-post" id="latest-post">
		<div class="container">
			<div class="stats-latest-post">
				<h4>Latest Post</h4>
				{% if latest_post is not None %}
					<p>{{ latest_post.status }}</p><br>
					<p>{{ latest_post.created_date }}</p><br>
				{% else %}
					<p>This user hasn't posted anything yet.</p>
				{% endif %}
			</div>
		</div>
	</section>

{% endblock %}

user_status/templates/user_status/user_status.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block title %}
Update Status ( &#64;{{ profile.name }} | fesbuk)
{% endblock %}

{% block style %}
<link href="{% static 'css/user_status.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<section name="input-status" id="input-status">
  <form id="form" method="POST" action="{% url 'status:add-status' %}">
    <h3>Update Status</h3>
      {% csrf_token %}
      {{ update_status_form }}
    <br>
    <input type="submit" value="Post" id="button" class="btn">
    </form>
</section>

<section name="list-status" id="list-status">
  <h3>Status</h3>
  {% if list %}
  <div class="flex">
    {% for data in list reversed %}
    <div class="flex-item">
      <img src="https://cdn4.iconfinder.com/data/icons/linecon/512/photo-128.png" alt="Profile Picture" id="image">
      <h4>{{ profile.name }}</h4>
      <p class="paragraph">{{ data.status }}</p>
      <p class="date">{{ data.created_date }}</p>
    </div>
    <br>
    {% endfor %}
  </div>
  {% else %}
    <p class="paragraph">{{ profile.name }} belum pernah Update Status</p>
  {% endif %}
</section>
{% endblock %}